/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.heter;

import org.apache.poi.hwpf.HWPFDocument;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class App {

    public File wordredaction(File oldFile) {
        File newFile = null;
        try (FileInputStream fileInputStream = new FileInputStream(oldFile);
             HWPFDocument document = new HWPFDocument(fileInputStream)) {


        } catch (IOException e) {
            e.printStackTrace();
        }
        return newFile;
    }


    public static void main(String[] args) {


    }
}
